"""Computed confidence.

Asking a model how confident it is produces a word, not a measurement. The word
is weakly correlated with correctness and is generated by the same process that
produced the claim, so it cannot serve as an independent check on it.

This computes a score from signals the model does not control:

| Factor                  | Why it bears on confidence                        |
|-------------------------|---------------------------------------------------|
| citation validity       | fabricated IDs are direct evidence of confabulation|
| claim coverage          | uncited conclusions are assertions, not findings   |
| lexical overlap         | cited evidence that shares no vocabulary is weak   |
| input parse rate        | unparsed input means the analysis ran on fragments |
| context completeness    | a chunked or compressed view saw less              |
| contradicting evidence  | looking for disconfirmation is a quality signal    |
| alternative hypotheses  | a single explanation considered is a warning sign  |
| evidence density        | one line supporting a root cause is thin           |

The model's own rating is carried alongside but contributes nothing to the
score. Where the two disagree the response says so explicitly -- an
`overconfident` flag is more useful to a reader than either number alone.

The weights are a defensible starting point, not a calibrated model. Honest
framing: this measures how well-evidenced an answer is, which is not the same
as whether it is correct, and the API says exactly that.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from .grounding import GroundingReport

_WORD_TO_SCORE = {"high": 0.85, "medium": 0.55, "low": 0.25}


@dataclass
class Factor:
    name: str
    value: float
    weight: float
    detail: str

    @property
    def contribution(self) -> float:
        return self.value * self.weight


@dataclass
class ConfidenceResult:
    score: float
    band: str
    factors: list[Factor] = field(default_factory=list)
    model_claimed: str | None = None
    warnings: list[str] = field(default_factory=list)

    @property
    def overconfident(self) -> bool:
        if not self.model_claimed:
            return False
        return _WORD_TO_SCORE.get(self.model_claimed, 0.5) - self.score > 0.25

    def public(self) -> dict:
        return {
            "computed_score": round(self.score, 3),
            "computed_band": self.band,
            "model_claimed_band": self.model_claimed,
            "model_overconfident": self.overconfident,
            "factors": [
                {
                    "name": f.name,
                    "value": round(f.value, 3),
                    "weight": f.weight,
                    "detail": f.detail,
                }
                for f in self.factors
            ],
            "warnings": self.warnings,
            "basis": (
                "Computed from citation validity, evidence coverage and input completeness. "
                "This measures how well-evidenced the analysis is, not whether it is correct."
            ),
        }


def _band(score: float) -> str:
    if score >= 0.70:
        return "high"
    if score >= 0.45:
        return "medium"
    return "low"


def compute_confidence(
    grounding: GroundingReport,
    *,
    parse_rate: float,
    context_strategy: str,
    model_claimed: str | None = None,
    contradicting_count: int = 0,
    alternatives_count: int = 0,
    root_cause_evidence_count: int = 0,
) -> ConfidenceResult:
    """Score how well-evidenced an analysis is."""
    warnings: list[str] = []
    factors: list[Factor] = []

    # 1. Citation validity. A fabrication is disqualifying, not a deduction.
    validity = grounding.grounding_ratio
    if grounding.has_fabrications:
        warnings.append(
            f"Fabricated evidence IDs: {', '.join(grounding.invalid_citations[:5])}. "
            f"These do not exist in the parsed input."
        )
    factors.append(
        Factor("citation_validity", validity, 0.30, f"{grounding.total_citations} citations, ratio {validity:.2f}")
    )

    # 2. Claim coverage.
    coverage = grounding.claim_coverage
    if coverage < 0.6 and grounding.uncited_claims:
        warnings.append(f"{len(grounding.uncited_claims)} claims carry no evidence reference.")
    factors.append(Factor("claim_coverage", coverage, 0.20, f"{coverage:.0%} of claims carry a valid citation"))

    # 3. Lexical overlap between claims and their cited evidence.
    overlap = (
        sum(c.lexical_overlap for c in grounding.checks) / len(grounding.checks)
        if grounding.checks
        else 0.0
    )
    # Overlap is a weak signal; normalize so a modest value is not punished.
    normalized_overlap = min(1.0, overlap / 0.35)
    factors.append(Factor("evidence_relevance", normalized_overlap, 0.10, f"mean term overlap {overlap:.2f}"))

    # 4. Input parse rate.
    if parse_rate < 0.5:
        warnings.append(f"Only {parse_rate:.0%} of input lines parsed into structured fields.")
    factors.append(Factor("input_parse_rate", parse_rate, 0.15, f"{parse_rate:.0%} of input parsed"))

    # 5. Context completeness.
    completeness = {
        "full": 1.0,
        "summary": 0.75,
        # A relevance-selected view is a deliberate subset: high-value lines are
        # present, the rest are represented only as pattern counts.
        "selected": 0.6,
        "map_reduce": 0.55,
    }.get(context_strategy, 0.5)
    if context_strategy != "full":
        warnings.append(
            f"The model saw a {context_strategy} view of the input, not the whole thing."
        )
    factors.append(Factor("context_completeness", completeness, 0.10, f"strategy: {context_strategy}"))

    # 6. Did the analysis look for disconfirming evidence?
    disconfirmation = min(1.0, contradicting_count / 2)
    if contradicting_count == 0:
        warnings.append("No contradicting evidence was identified; the analysis may be one-sided.")
    factors.append(
        Factor("disconfirmation_sought", disconfirmation, 0.08, f"{contradicting_count} contradicting items")
    )

    # 7. Were alternatives considered?
    alternatives = min(1.0, alternatives_count / 2)
    if alternatives_count == 0:
        warnings.append("No alternative hypotheses were offered.")
    factors.append(Factor("alternatives_considered", alternatives, 0.07, f"{alternatives_count} alternatives"))

    score = sum(f.contribution for f in factors)

    # A thin root cause caps the score regardless of everything else.
    if root_cause_evidence_count <= 1:
        score = min(score, 0.60)
        warnings.append(
            f"The root cause rests on {root_cause_evidence_count} piece(s) of evidence; "
            f"confidence is capped accordingly."
        )

    # Any fabrication caps it harder. An analysis that invented a citation has
    # demonstrated the failure mode this whole layer exists to catch.
    if grounding.has_fabrications:
        score = min(score, 0.35)

    score = max(0.0, min(1.0, score))

    return ConfidenceResult(
        score=score,
        band=_band(score),
        factors=factors,
        model_claimed=model_claimed,
        warnings=warnings,
    )
